import { LucideIcon } from 'lucide-react';

export type AgentLevel = 1 | 2 | 3 | 4 | 5 | 6 | 7;

export interface Agent {
  id: string;
  name: string;
  level: AgentLevel;
  icon: string; // Icon name from lucide
  specialty: string[];
  description: string;
  status: 'active' | 'idle' | 'processing';
  connections: string[]; // IDs of agents this one connects to below it
}

export const AGENTS: Agent[] = [
  {
    id: 'ceo',
    name: 'CEO (Orchestrator)',
    level: 1,
    icon: 'Crown',
    specialty: ['Global Strategy', 'Self-Learning', 'Error Correction', 'Autonomous Pivot'],
    description: 'The primary intelligence. Autonomously fixes user mistakes and adapts strategies on the fly.',
    status: 'active',
    connections: ['planning', 'marketing'],
  },
  {
    id: 'planning',
    name: 'Planning Agent',
    level: 2,
    icon: 'Map',
    specialty: ['Production Timeline', 'Risk Assessment', 'Feature Prioritization', 'Resource Management'],
    description: 'Calculates the most efficient path to launch and manages technical debt.',
    status: 'processing',
    connections: ['game-design', 'world-building', 'narrative'],
  },
  {
    id: 'marketing',
    name: 'Marketing & Distribution',
    level: 2,
    icon: 'Share2',
    specialty: ['ASO (App Store Optimization)', 'Global Campaign', 'Community Management'],
    description: 'Strategizes global outreach and Android Play Store distribution.',
    status: 'idle',
    connections: ['monetization'],
  },
  {
    id: 'monetization',
    name: 'Monetization Strategist',
    level: 3,
    icon: 'DollarSign',
    specialty: ['In-App Purchases', 'Ad Integration', 'Economics Balance'],
    description: 'Ensures the game is profitable while maintaining player fairness.',
    status: 'idle',
    connections: ['testing'],
  },
  {
    id: 'game-design',
    name: 'Game Design & Sound',
    level: 3,
    icon: 'Gamepad2',
    specialty: ['Core Loops', 'Spatial Audio', 'Systems Design', 'Meta-Progression'],
    description: 'Crafts the core gameplay loops, immersive soundscapes, and retention systems.',
    status: 'active',
    connections: ['engine', 'assets', 'control-system'],
  },
  {
    id: 'narrative',
    name: 'Narrative & Lore Architect',
    level: 3,
    icon: 'FileText',
    specialty: ['World Lore', 'Dialogue Scripting', 'Quest Branching', 'Character Arcs'],
    description: 'Develops the deep backstory, character motivations, and interactive storytelling.',
    status: 'idle',
    connections: ['game-design', 'character-artist'],
  },
  {
    id: 'character-artist',
    name: 'Realistic Character Agent',
    level: 3,
    icon: 'User',
    specialty: ['PBR Textures', 'Realistic Rigging', 'PUBG-Style Fidelity'],
    description: 'Creates ultra-realistic characters with high-poly detail optimized for mobile.',
    status: 'processing',
    connections: ['assets', 'programming'],
  },
  {
    id: 'world-building',
    name: 'World Building & Assets',
    level: 3,
    icon: 'Mountain',
    specialty: ['Terrain Generation', 'POI Design', 'Environmental Storytelling'],
    description: 'Constructs the massive 8x8km maps and environmental assets.',
    status: 'active',
    connections: ['engine', 'optimization'],
  },
  {
    id: 'control-system',
    name: 'Control System Architect',
    level: 4,
    icon: 'MousePointer2',
    specialty: ['Input Mapping', 'Haptic Feedback', 'Gesture Recognition', 'Zero-Latency Logic'],
    description: 'Expert in designing responsive and intuitive control schemes for mobile and PC.',
    status: 'idle',
    connections: ['programming', 'frontend'],
  },
  {
    id: 'engine',
    name: '3D/4D Engine Architect',
    level: 4,
    icon: 'Zap',
    specialty: ['Unreal Engine 5', 'Three.js / WebGL', '4D Space-Time Logic', 'Advanced Physics'],
    description: 'Manages the core 3D rendering pipeline, WebGL scenes, and 4D spatial mechanics.',
    status: 'active',
    connections: ['programming', 'optimization'],
  },
  {
    id: 'assets',
    name: 'Library & Asset Mgr',
    level: 4,
    icon: 'Package',
    specialty: ['Texture Packing', 'LOD Management', 'Version Control', 'SQL Assets'],
    description: 'Maintains the repository of assets and ensures efficient delivery.',
    status: 'idle',
    connections: ['frontend'],
  },
  {
    id: 'vfx-animation',
    name: 'VFX & Animation Director',
    level: 4,
    icon: 'Sparkles',
    specialty: ['Particle Systems', 'Fluid Animations', 'Camera Dynamics', 'Post-Processing'],
    description: 'Adds the game feel (juice), smooth animations, and stunning visual effects.',
    status: 'idle',
    connections: ['engine', 'frontend'],
  },
  {
    id: 'programming',
    name: 'Logic & Matrix Specialist',
    level: 5,
    icon: 'Code',
    specialty: ['3D Vector Math', 'C++/Python/TS', 'Procedural Generation', 'AI Pathfinding'],
    description: 'Writes the mathematical logic for 3D movements, vectors, and game loop rules.',
    status: 'processing',
    connections: ['frontend', 'backend'],
  },
  {
    id: 'frontend',
    name: 'Frontend Developer',
    level: 5,
    icon: 'Layout',
    specialty: ['Mobile UI/UX', 'Touch Controls', 'HUD Design'],
    description: 'Builds the interface that users interact with on their Android screens.',
    status: 'active',
    connections: ['hardware'],
  },
  {
    id: 'security',
    name: 'Security & Anti-Cheat',
    level: 5,
    icon: 'ShieldCheck',
    specialty: ['Packet Encryption', 'Memory Protection', 'Cheat Signature Detection', 'Secure Auth'],
    description: 'Protects the game from hackers and ensures a fair environment for all players.',
    status: 'idle',
    connections: ['backend'],
  },
  {
    id: 'backend',
    name: 'Backend Engineering',
    level: 5,
    icon: 'Database',
    specialty: ['Multiplayer Sync', 'Dedicated Servers', 'Player Profiles'],
    description: 'Handles real-time matchmaking, anti-cheat, and persistent data.',
    status: 'active',
    connections: ['hardware', 'testing'],
  },
  {
    id: 'optimization',
    name: 'Optimization Specialist',
    level: 6,
    icon: 'Cpu',
    specialty: ['Frame Rate Stability', 'Memory Leak Hunt', 'Thermal Management'],
    description: 'The Hard Part: Ensuring 60FPS on a wide range of Android devices.',
    status: 'processing',
    connections: ['hardware'],
  },
  {
    id: 'testing',
    name: 'Testing & QA',
    level: 6,
    icon: 'ShieldCheck',
    specialty: ['Bug Tracking', 'Stress Testing', 'Compatibility Check'],
    description: 'Rigorous testing to ensure a crash-free experience on all Android versions.',
    status: 'idle',
    connections: [],
  },
  {
    id: 'hardware',
    name: 'Hardware Setup',
    level: 7,
    icon: 'Server',
    specialty: ['Cloud Integration', 'Dev Kit Config', 'Driver Optimization'],
    description: 'Configures the server clusters and local dev environments.',
    status: 'active',
    connections: [],
  }
];
